name: CI

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'zulu'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Run tests
      run: |
        ./gradlew clean -D spring.profiles.active=test test
        if [ $? -eq 0 ]; then
            echo "success"
          else
            echo "fail"
            exit 1
          fi
